name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Set environment variable for GitHub Actions
      run: echo "RUNNING_IN_GITHUB_ACTIONS=true" >> $GITHUB_ENV

    - name: Run Model Quality Pipeline in SageMaker
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
        ROLE: ${{ secrets.AWS_ROLE }}
        BUCKET: ${{ secrets.AWS_BUCKET }}
        COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
        COMET_PROJECT_NAME: ${{ secrets.COMET_PROJECT_NAME }}
        PIPELINE_MODEL_PACKAGE_GROUP: ${{ secrets.PIPELINE_MODEL_PACKAGE_GROUP }}
        MAE_THRESHOLD: ${{ secrets.MAE_THRESHOLD }}
        RUNNING_IN_GITHUB_ACTIONS: ${{ env.RUNNING_IN_GITHUB_ACTIONS }}

      run: |
        python aws_pipelines/model_quality_pipeline.py

